### ISSUE TITLE
Push fails: put branchName in docs. if branch is undefined don't put it in the git push args.

### ISSUE THREAD

**Issue by kkruit** [caitp/grunt-bower-release#25]
After running the code was never pushed.

When run with -v I'd get the following:

```
git push origin  0.3.15
Username for 'https://git.com/repo.git': kkruit
Password for 'https://kkruit@git.com/repo.git': 
error: src refspec undefined does not match any.
error: failed to push some refs to 'https://git.com/repo.git'
```

Turns out it is actaully calling:

```
git push origin undefined 0.3.15
```

Because "branchName" is undefined. 

Suggested Resolution:
Docs needs branchName defined as an option.

git.js endpoint needs to not put branchName in args if it's undefined

I'm planning on making a PR which is a simple fix but I would really like to tighten the testing net to include this which means a test for the endpoint is needed.

**Comment by kkruit** [comment]
If anyone else runs into this issue... a current work around is to specify 'branchName' in your options.

**Comment by caitp** [comment]
hmm, I can't recall why it pushes branch names. but yeah, a fix would be good. it might make sense to just remove branch pushing entirely, but optional works too
