### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by mikeborozdin** [caitp/grunt-bower-release#36]
I've cloned the repository and just run 'grunt test' unfortunately I've got a message saying:

```
Warning: 2/24 assertions failed (179ms) Use --force to continue.

Aborted due to warnings.
```

Interestingly, I can see the same message in [Travis CI](https://travis-ci.org/caitp/grunt-bower-release). So, the problem is persistent and is not related to my local environment.

**Comment by mikeborozdin** [comment]
Hi @caitp,

I've submitted a pull request fixing the problem - https://github.com/caitp/grunt-bower-release/pull/37

**Comment by caitp** [comment]
Closed by https://github.com/caitp/grunt-bower-release/commit/db67d5c5dd60d9a7c9799c4ab182720d481ce138
