### ISSUE TITLE
Fatal error: Unable to write "src" file (Error code: EISDIR).

### ISSUE THREAD

**Issue by kkruit** [caitp/grunt-bower-release#5]
When I try using this I get the above error. It is creating a cwd directory and i'm guessing it's trying to create src directory which already exists. 

It does create the dist-push directory with the contents of the endpoint just fine.

My bowerRelease config:

```
  bowerRelease: {
      options: {
        main: 'lib.tmpl.min.js'
      },
      prod: {
        options: {
          endpoint: 'https://some.domain.com:8443/lib.git',
          stageDir: 'dist-push'
        },
        files: {
          cwd: 'dist',
          src: ['lib.js', 'lib.min.js', 'lib.tmpl.min.js', 'templates.js', 'bower.json']
        }
  }
```

**Comment by kkruit** [comment]
I've found more information. The original src had '*.*' so I specifically defined each one to make sure that was not the issue. The actual problem occurs when you have the bower.json included in your src. So I'm not sure if you'd still consider it a bug or not but much less of an issue than I originally thought.

**Comment by caitp** [comment]
Hmmm interesting, so if you try to include bower.json it will have problems?

That's something that should be pretty trivial to fix in the task, do you want to send a PR?

**Comment by kkruit** [comment]
Okay, looking at the documentation of grunt file configurations, it appears that you cannot use 'cwd' unless the expand option is set to true. The bower.json because it was in the root of my project was just changing the behavior. Your code works fine however I will make a PR for adding expand to the files option in your read me. Thanks for your tool it's pretty great. :)
