### ISSUE TITLE
When using cwd with expand files are being put in wrong dest.

### ISSUE THREAD

**Issue by kkruit** [caitp/grunt-bower-release#8]
When I don't enter a dest and I use cwd it's placing all files in {stageDir}/{files:cwd}/{files:src} instead of {stageDir}/{files:src}.

**Comment by caitp** [comment]
PRs welcome! I basically haven't used this package at all except for one project, where it worked fairly well. So there's obviously no real test suite or anything to guard against regressions or anything (it would probably be good to add one if people are actually using this for things)

So if you're interested in this, I'm more than happy to take a patch, it's probably a pretty minor adjustment to the task to make this work. Tests would be helpful, but I feel like grunt tasks are a bit tricky to test :( In any case, I am happy to merge a fix if you come up with one.

**Comment by kkruit** [comment]
Yeah. I'm working on it just wanted to have an issue to assign a pr to. Thanks.

**Comment by caitp** [comment]
Also fixed by #10 ?
